#
###################################
# Site wide configuration
####################################
#
author: Kevin Thielen
title: KevinThielen's Portfolio
email: GenusNymphicus@gmail.com
description: My humble portfolio
url: 
keywords: ["GameDev", "Portfolio", "Freelancer"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Berlin
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Kevin Thielen
  avatar: avatar.png
  # bio: "Independent Game Developer and passionate programmer"
  email: GenusNymphicus@gmail.com
  
  github: KevinThielen #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:


theme: jekyll-theme-cayman